{% set name = "pyepr" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bbaf240c88a0e206b55e927146ea432501062ac8aa72e567ae16fc1817586d0f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - packaging
    - numpy >=1.7
    - cython >=0.29.22
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - packaging
  source_files:
    - tests/test_all.py
  imports:
    - epr

about:
  home: https://avalentino.github.com/pyepr
  license: GPL-3.0-or-later
  license_family: GPL
  license_file:
    - LICENSE.txt
  summary: Python ENVISAT Product Reader API

  description: |
    PyEPR provides Python bindings for the ENVISAT Product Reader C API
    (EPR API) for reading satellite data from ENVISAT ESA (European Space
    Agency) mission.
    PyEPR, as well as the EPR API for C, supports ENVISAT MERIS, AATSR
    Level 1B and Level 2 and also ASAR data products. It provides access to
    the data either on a geophysical (decoded, ready-to-use pixel samples)
    or on a raw data layer. The raw data access makes it possible to read
    any data field contained in a product file.
  doc_url: https://avalentino.github.io/pyepr/html/index.html
  dev_url: https://github.com/avalentino/pyepr

extra:
  recipe-maintainers:
    - avalentino
