{% set name = "pyepr" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0094223196d4ea2ba1371f0eb42da8e9f7fd1872101dda810111f48e95d9de09

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy >=1.7
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - unittest2  # [py2k]
  source_files:
    - tests/test_all.py
  imports:
    - epr

about:
  home: https://avalentino.github.com/pyepr
  license: GPL-3.0
  license_family: GPL
  license_file:
    - LICENSE.txt
    - LICENSES/epr-api.txt
  summary: Python ENVISAT Product Reader API

  description: |
    PyEPR provides Python bindings for the ENVISAT Product Reader C API
    (EPR API) for reading satellite data from ENVISAT ESA (European Space
    Agency) mission.
    PyEPR, as well as the EPR API for C, supports ENVISAT MERIS, AATSR
    Level 1B and Level 2 and also ASAR data products. It provides access to
    the data either on a geophysical (decoded, ready-to-use pixel samples)
    or on a raw data layer. The raw data access makes it possible to read
    any data field contained in a product file.
  doc_url: https://avalentino.github.io/pyepr/html/index.html
  dev_url: https://github.com/avalentino/pyepr

extra:
  recipe-maintainers:
    - avalentino
